apiVersion: v1
kind: Service
metadata:
  namespace: code
  name: code-server-service
spec:
  selector:
    app: code-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: code
  name: code-ingress
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "code.lab.local"
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  rules:
  - host: code.lab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: code-server-service
            port:
              number: 8080
