apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: code
  name: code-server-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
