---
apiVersion: v1
kind: Secret
metadata:
  name: mikrotik-credentials
  namespace: external-dns
stringData:
  MIKROTIK_BASEURL: "https://192.168.10.200:443"
  MIKROTIK_USERNAME: "dns"
  MIKROTIK_PASSWORD: "dns"
  MIKROTIK_SKIP_TLS_VERIFY: "true"
